### ISSUE TITLE
Reqs cost warning - take currency conversion into account

### ISSUE THREAD

**Issue by iaincrawf** [linn/purchasing#304]
Message doesn't take currency into account, so other currencies which are many to 1 pound can display message unecessarily, ie this one with 18000 yen which is apparently under £200 in value https://app.linn.co.uk/purchasing/purchase-orders/reqs/15211

Could if we fancied do currency conversion to check the GBP value before showing it. Not sure it's a big issue as maybe not that common and users are free to just ignore it, but would be an enhancement and Petra made a ticket querying it
![image](https://user-images.githubusercontent.com/51612225/186882665-ed5d91e7-fb06-4b40-9f2b-21fa9b2d33d1.png)

**Comment by richardiphillips** [comment]
yeah the old form definitely did the currency conversion so we should do it here too.
