### ISSUE TITLE
PO : Requested Date + Net total, Base Net total, detail total , Base detail total not being initialised properly 

### ISSUE THREAD

**Issue by RossStewart** [linn/purchasing#400]
Net total, Base Net total, detail total , Base detail total not being pulled through from MR. 

Works fine from the quick create but details are blank when coming from MR

**Comment by richardiphillips** [comment]
MR just calls with the specified querystring supplierId=123&partNumber=abc etc. 

This order must not be initialised properly from this

**Comment by RossStewart** [comment]
Merging the two issues. 

Original description :

"Andy wants to see the requested date on the Create screen.

This should default to the lead time + delivery day e.g. if a Supplier has a delivery date of thursday, it would be leadtime + 4 days.

If a supplier has no delivery date, it should default to 2 weeks."

**Comment by richardiphillips** [comment]
I didn't raise the other issue. These two are different issues

**Comment by RossStewart** [comment]
Sorry, my mistake - see what you meant now.
