### ISSUE TITLE
BUG: You can raise a purchase order for a part with another part's price if it shares the same root

### ISSUE THREAD

**Issue by andrewfraser73** [linn/purchasing#466]
See Stephen Wallace ticket [](http://pchelpdesk.linn.co.uk/scp/tickets.php?id=16652)

The problem is that a part-suppliers search for MCP 3009/A also brings back the record for MCP 3009/AB
https://app.linn.co.uk/purchasing/part-suppliers?searchTerm=&partNumber=MCP%203009/A

To reproduce go to
http://app.linn.co.uk/purchasing/purchase-orders/quick-create
- type MCP 3009/A into part search
- note there is two Metro Engineerings in the Supplier list
- note the price is 62 not 52 like it should be

You can also replicate this on the part supplier lookup with search term MCP 3009/AB you will see two

**Comment by andrewfraser73** [comment]
ticket is http://pchelpdesk.linn.co.uk/scp/tickets.php?id=16652

**Comment by richardiphillips** [comment]
sorted
